/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EjercisioHerencia;
import EjercisioHerencia.Electrodomestico;
import EjercisioHerencia.Lavadora;
import EjercisioHerencia.Television;
/**
 *
 * @author ODRAUDE MENDEZ AGUIRRE
 */
public class Ejecutable extends javax.swing.JFrame {
    private float precioBase,peso,carga,precioFinal;
    private int resolucion;
    private boolean sintonizador;
    private String consumoEnergetico, color;
    

    /**
     * Creates new form Ejecutable
     */
    public Ejecutable() {
        initComponents();
        esconderCampos1();
        esconderCampos2();
        esconderCampos3();
    }
    
    public void esconderCampos1(){
        txtPrecioBase1.hide();
        txtPeso1.hide();
        txtConsumo1.hide();
        rddlColor1.hide();
        btn1.hide();
    }
    public void esconderCampos2(){
        txtResolucion.hide();
        txtPrecioBase2.hide();
        txtPeso2.hide();
        txtConsumo2.hide();
        rddlColor2.hide();
        rbtnSintonizador.hide();
        btn2.hide();
    }
    public void esconderCampos3(){
        txtCarga.hide();
        txtPrecioBase3.hide();
        txtPeso3.hide();
        txtConsumo3.hide();
        rddlColor3.hide();
        btn3.hide();
    }
    public void mostrarCampos1(){
        txtPrecioBase1.show(true);
        txtPeso1.show(true);
        txtConsumo1.show(true);
        rddlColor1.show(true);
        btn1.show(true);
    }
    public void mostrarCampos2(){
        txtResolucion.show(true);
        txtPrecioBase2.show(true);
        txtPeso2.show(true);
        txtConsumo2.show(true);
        rddlColor2.show(true);
        rbtnSintonizador.show(true);
        btn2.show(true);
    }
    public void mostrarCampos3(){
        txtCarga.show(true);
        txtPrecioBase3.show(true);
        txtPeso3.show(true);
        txtConsumo3.show(true);
        rddlColor3.show(true);
        btn3.show(true);
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnelectrodomestico = new javax.swing.JButton();
        btnTelevision = new javax.swing.JButton();
        btnLavadora = new javax.swing.JButton();
        txtPrecioBase1 = new javax.swing.JTextField();
        txtPeso1 = new javax.swing.JTextField();
        txtConsumo1 = new javax.swing.JTextField();
        txtResolucion = new javax.swing.JTextField();
        txtPrecioBase2 = new javax.swing.JTextField();
        txtPeso2 = new javax.swing.JTextField();
        txtConsumo2 = new javax.swing.JTextField();
        txtCarga = new javax.swing.JTextField();
        txtPrecioBase3 = new javax.swing.JTextField();
        txtPeso3 = new javax.swing.JTextField();
        txtConsumo3 = new javax.swing.JTextField();
        rbtnSintonizador = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rddlColor2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        rddlColor1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        rddlColor3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtpnPanel = new javax.swing.JTextPane();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnelectrodomestico.setText("Electrodomestico");
        btnelectrodomestico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnelectrodomestico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnelectrodomesticoMouseClicked(evt);
            }
        });
        getContentPane().add(btnelectrodomestico);
        btnelectrodomestico.setBounds(70, 38, 113, 23);

        btnTelevision.setText("Television");
        btnTelevision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTelevisionMouseClicked(evt);
            }
        });
        getContentPane().add(btnTelevision);
        btnTelevision.setBounds(296, 38, 105, 23);

        btnLavadora.setText("Lavadora");
        btnLavadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLavadoraMouseClicked(evt);
            }
        });
        getContentPane().add(btnLavadora);
        btnLavadora.setBounds(592, 38, 100, 23);

        txtPrecioBase1.setText("Precio Base");
        getContentPane().add(txtPrecioBase1);
        txtPrecioBase1.setBounds(70, 79, 113, 30);

        txtPeso1.setText("Peso");
        getContentPane().add(txtPeso1);
        txtPeso1.setBounds(70, 117, 113, 30);

        txtConsumo1.setText("Consumo Energetico");
        getContentPane().add(txtConsumo1);
        txtConsumo1.setBounds(70, 155, 113, 30);

        txtResolucion.setText("Resolucion");
        getContentPane().add(txtResolucion);
        txtResolucion.setBounds(296, 69, 105, 30);

        txtPrecioBase2.setText("Precio Base");
        getContentPane().add(txtPrecioBase2);
        txtPrecioBase2.setBounds(296, 110, 105, 30);

        txtPeso2.setText("Peso");
        getContentPane().add(txtPeso2);
        txtPeso2.setBounds(296, 148, 105, 30);

        txtConsumo2.setText("Consumo Energetico");
        getContentPane().add(txtConsumo2);
        txtConsumo2.setBounds(296, 186, 105, 30);

        txtCarga.setText("Carga");
        getContentPane().add(txtCarga);
        txtCarga.setBounds(592, 69, 100, 30);

        txtPrecioBase3.setText("Precio Base");
        getContentPane().add(txtPrecioBase3);
        txtPrecioBase3.setBounds(592, 107, 100, 30);

        txtPeso3.setText("Peso");
        getContentPane().add(txtPeso3);
        txtPeso3.setBounds(592, 145, 100, 30);

        txtConsumo3.setText("Consumo Energetico");
        getContentPane().add(txtConsumo3);
        txtConsumo3.setBounds(592, 183, 105, 30);

        rbtnSintonizador.setText("Sintonizador");
        getContentPane().add(rbtnSintonizador);
        rbtnSintonizador.setBounds(296, 319, 85, 23);

        rddlColor2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "blanco", "negro", "rojo", "azul", "gris" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rddlColor2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rddlColor2.setToolTipText("");
        jScrollPane1.setViewportView(rddlColor2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(296, 231, 113, 86);

        rddlColor1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "blanco", "negro", "rojo", "azul", "gris" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rddlColor1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rddlColor1.setToolTipText("");
        jScrollPane2.setViewportView(rddlColor1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 201, 113, 86);

        rddlColor3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "blanco", "negro", "rojo", "azul", "gris" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rddlColor3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rddlColor3.setToolTipText("");
        jScrollPane3.setViewportView(rddlColor3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(592, 231, 113, 86);

        jScrollPane4.setViewportView(txtpnPanel);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(201, 374, 326, 140);

        btn1.setText("OK");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(89, 302, 47, 23);

        btn2.setText("OK");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(334, 349, 47, 23);

        btn3.setText("OK");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(640, 337, 47, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnelectrodomesticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnelectrodomesticoMouseClicked
        // TODO add your handling code here:
        esconderCampos2();
        esconderCampos3();
        mostrarCampos1();
    }//GEN-LAST:event_btnelectrodomesticoMouseClicked

    private void btnTelevisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTelevisionMouseClicked
        // TODO add your handling code here:
        esconderCampos1();
        esconderCampos3();
        mostrarCampos2();
    }//GEN-LAST:event_btnTelevisionMouseClicked

    private void btnLavadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLavadoraMouseClicked
        // TODO add your handling code here:
        esconderCampos1();
        esconderCampos2();
        mostrarCampos3();
    }//GEN-LAST:event_btnLavadoraMouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        precioBase=Float.parseFloat(txtPrecioBase1.getText());
        peso=Float.parseFloat(txtPeso1.getText());
        consumoEnergetico=txtConsumo1.getText();
        color=rddlColor1.getSelectedValue();
        Electrodomestico electrodomestico = new Electrodomestico(precioBase,peso,consumoEnergetico,color);
        txtpnPanel.setText("Especificaciones del Electrodomestico:\nPrecio base: "+precioBase+"\n"+ 
                "peso: "+electrodomestico.setPeso()+"\n"+"ConsumoEnergetico: "+electrodomestico.setConsumo()+"\n"+
                "color: "+electrodomestico.setColor()+"\n"+"Precio Final: "+electrodomestico.setPrecio());
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        precioBase=Float.parseFloat(txtPrecioBase2.getText());
        peso=Float.parseFloat(txtPeso2.getText());
        consumoEnergetico=txtConsumo2.getText();
        color=rddlColor2.getSelectedValue();
        resolucion=Integer.parseInt(txtResolucion.getText());
        sintonizador=rbtnSintonizador.isSelected();
        Television tele= new Television(resolucion,sintonizador,precioBase,peso,consumoEnergetico,color);
        precioFinal=tele.precioFinal(tele.setPrecio());
        txtpnPanel.setText("Especificaciones de la Television:\nPrecio base: "+precioBase+"\n"+ 
                "peso: "+tele.setPeso()+"\n"+"ConsumoEnergetico: "+tele.setConsumo()+"\n"+
                "color: "+tele.setColor()+"\n"+"resolucion: "+tele.setRes()+"\n"+"Sintonizador: "+tele.setSin()+"\n"+"Precio Final: "+ precioFinal);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        precioBase=Float.parseFloat(txtPrecioBase3.getText());
        peso=Float.parseFloat(txtPeso3.getText());
        consumoEnergetico=txtConsumo3.getText();
        color=rddlColor3.getSelectedValue();
        carga= Float.parseFloat(txtCarga.getText());
        Lavadora lavadora = new Lavadora(carga,precioBase,peso,consumoEnergetico,color);
        precioFinal=lavadora.precioFinal(lavadora.setPrecio());
        txtpnPanel.setText("Especificaciones de la Lavadora:\nPrecio base: "+precioBase+"\n"+ 
                "peso: "+lavadora.setPeso()+"\n"+"ConsumoEnergetico: "+lavadora.setConsumo()+"\n"+
                "color: "+lavadora.setColor()+"\n"+"Carga: "+lavadora.setCarga()+"\n"+"Precio Final: "+precioFinal);
    }//GEN-LAST:event_btn3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecutable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecutable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnLavadora;
    private javax.swing.JButton btnTelevision;
    private javax.swing.JButton btnelectrodomestico;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rbtnSintonizador;
    private javax.swing.JList<String> rddlColor1;
    private javax.swing.JList<String> rddlColor2;
    private javax.swing.JList<String> rddlColor3;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtConsumo1;
    private javax.swing.JTextField txtConsumo2;
    private javax.swing.JTextField txtConsumo3;
    private javax.swing.JTextField txtPeso1;
    private javax.swing.JTextField txtPeso2;
    private javax.swing.JTextField txtPeso3;
    private javax.swing.JTextField txtPrecioBase1;
    private javax.swing.JTextField txtPrecioBase2;
    private javax.swing.JTextField txtPrecioBase3;
    private javax.swing.JTextField txtResolucion;
    private javax.swing.JTextPane txtpnPanel;
    // End of variables declaration//GEN-END:variables
}
